# Generated by Django 5.0.6 on 2026-07-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='academic_year',
            field=models.CharField(choices=[('200', 'Level 200'), ('300', 'Level 300')], default=200, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('information_technology', 'Information Technology'), ('business_administration', 'Business Administration'), ('accountancy', 'Accountancy'), ('marketing', 'Marketing'), ('procurement_and_supply', 'Procurement and Supply'), ('statistics', 'Statistics'), ('other', 'Other')], default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='program_of_study',
            field=models.CharField(choices=[('hnd', 'HND'), ('degree', "Bachelor's Degree"), ('degree_topup', "Bachelor's Degree (Top-up)"), ('diploma', 'Diploma')], default='dip_computer_science', max_length=50),
            preserve_default=False,
        ),
    ]
