# Generated by Django 5.0.6 on 2026-07-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_academic_year_registration_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.CharField(choices=[('computer_science', 'Department of Computer Science'), ('information_systems_technology', 'Department of Information Systems & Technology'), ('business_computing', 'Department of Business Computing'), ('cyber_security_computer_engineering', 'Department of Cyber Security & Computer Engineering Technology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='program_of_study',
            field=models.CharField(choices=[('bsc_computer_science', 'B.Sc. in Computer Science'), ('bsc_data_science', 'B.Sc. in Data Science'), ('bsc_network_science', 'B.Sc. in Network Science'), ('dip_computer_science', 'Diploma in Computer Science'), ('bsc_information_technology', 'B.Sc. in Information Technology'), ('bsc_information_systems', 'B.Sc. in Information Systems'), ('bsc_computing_with_accounting', 'B.Sc. in Computing-With-Accounting'), ('bsc_cyber_security', 'B.Sc. in Cyber Security'), ('bsc_software_engineering', 'B.Sc. in Software Engineering'), ('dip_cyber_security', 'Diploma in Cyber Security'), ('dip_software_engineering', 'Diploma in Software Engineering')], max_length=50),
        ),
    ]
